export const FETCH_SUCESS = 'FETCH_SUCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const FETCH_LOADING = 'FETCH_LOADING';


export const FETCH_IMAGE_SUCESS = 'FETCH_IMAGE_SUCESS';
export const FETCH_IMAGE_FAIL = 'FETCH_IMAGE_FAIL';
export const FETCH_IMAGE_LOADING = 'FETCH_IMAGE_LOADING'